apiVersion: v1
kind: Pod
metadata:
    labels:
        run: fortune2s
    name: fortune2s
spec:
    containers:
        - image: szumigalskis/fortune:args
          args: ["2"]
          name: html-generator
          volumeMounts:
          - name: html
            mountPath: /var/htdocs
        - image: nginx:alpine
          name: webserver
          volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
            readOnly: true
          ports:
          - containerPort: 80
            protocol: TCP
    volumes:
      - name: html
        emptyDir: {}        