apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    name: webapp
    imagePullPolicy: Always
    envFrom:
    - secretRef:
        name: db-secret