apiVersion: apps/v1
kind: Deployment
metadata:
  name: drain
spec:
  replicas: 30
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: alpine