apiVersion: v1
kind: Pod
metadata:
    name: my-pod
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
      - mountPath: /test-pd
        name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /var
       # this field is optional
      type: Directory